DEFAULT_INITIAL_CAPITAL = 10000.0
DEFAULT_COMMISSION_PCT = 0.001
DEFAULT_SLIPPAGE_PCT = 0.0005
DEFAULT_POSITION_SIZE_PCT = 0.02
DEFAULT_MAX_POSITIONS = 1

ATR_STOP_MULTIPLIER = 1.5
ATR_TP1_MULTIPLIER = 2.0
ATR_TP2_MULTIPLIER = 3.5
PARTIAL_TP1_PERCENT = 0.5

TRAILING_STOP_ACTIVATION_PCT = 0.01
TRAILING_STOP_DISTANCE_PCT = 0.005
BREAK_EVEN_ACTIVATION_PCT = 0.005

WALK_FORWARD_WINDOWS = 5
WALK_FORWARD_TRAIN_PCT = 0.7
WALK_FORWARD_TEST_PCT = 0.3

MONTE_CARLO_SIMULATIONS = 1000
MONTE_CARLO_CONFIDENCE = 0.95

ROBUSTNESS_PARAMETER_NOISE = 0.05
ROBUSTNESS_SENSITIVITY_THRESHOLD = 0.1

OPTIMIZATION_DEFAULT_RUNS = 50

TARGET_WIN_RATE = 0.50
TARGET_PROFIT_FACTOR = 2.50
TARGET_MAX_DRAWDOWN = 0.10
TARGET_EXPECTANCY_POSITIVE = True

RISK_FREE_RATE = 0.02
TRADING_DAYS_PER_YEAR = 252
HOURS_PER_DAY = 24
